server:
  port: 8085
  servlet:
    context-path: /boubyan
spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect